# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/shlab_89/Desktop/lab1/lab1.srcs/sources_1/bd/face/ip/face_processing_system7_0_0/face_processing_system7_0_0.xci
# IP: The module: 'face_processing_system7_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/shlab_89/Desktop/lab1/lab1.srcs/sources_1/bd/face/ip/face_processing_system7_0_0/face_processing_system7_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'face_processing_system7_0_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst]

# IP: c:/Users/shlab_89/Desktop/lab1/lab1.srcs/sources_1/bd/face/ip/face_processing_system7_0_0/face_processing_system7_0_0.xci
# IP: The module: 'face_processing_system7_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/shlab_89/Desktop/lab1/lab1.srcs/sources_1/bd/face/ip/face_processing_system7_0_0/face_processing_system7_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'face_processing_system7_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst]
