# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/0416313_lab4/0416313_lab4.srcs/sources_1/bd/lab4/ip/lab4_rst_ps7_0_100M_3/lab4_rst_ps7_0_100M_3.xci
# IP: The module: 'lab4_rst_ps7_0_100M_3' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/0416313_lab4/0416313_lab4.srcs/sources_1/bd/lab4/ip/lab4_rst_ps7_0_100M_3/lab4_rst_ps7_0_100M_3_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'lab4_rst_ps7_0_100M_3'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0]

# XDC: c:/0416313_lab4/0416313_lab4.srcs/sources_1/bd/lab4/ip/lab4_rst_ps7_0_100M_3/lab4_rst_ps7_0_100M_3.xdc
# XDC: The top module name and the constraint reference have the same name: 'lab4_rst_ps7_0_100M_3'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]

# XDC: c:/0416313_lab4/0416313_lab4.srcs/sources_1/bd/lab4/ip/lab4_rst_ps7_0_100M_3/lab4_rst_ps7_0_100M_3_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'lab4_rst_ps7_0_100M_3'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]

# IP: C:/0416313_lab4/0416313_lab4.srcs/sources_1/bd/lab4/ip/lab4_rst_ps7_0_100M_3/lab4_rst_ps7_0_100M_3.xci
# IP: The module: 'lab4_rst_ps7_0_100M_3' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/0416313_lab4/0416313_lab4.srcs/sources_1/bd/lab4/ip/lab4_rst_ps7_0_100M_3/lab4_rst_ps7_0_100M_3_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'lab4_rst_ps7_0_100M_3'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]

# XDC: c:/0416313_lab4/0416313_lab4.srcs/sources_1/bd/lab4/ip/lab4_rst_ps7_0_100M_3/lab4_rst_ps7_0_100M_3.xdc
# XDC: The top module name and the constraint reference have the same name: 'lab4_rst_ps7_0_100M_3'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]

# XDC: c:/0416313_lab4/0416313_lab4.srcs/sources_1/bd/lab4/ip/lab4_rst_ps7_0_100M_3/lab4_rst_ps7_0_100M_3_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'lab4_rst_ps7_0_100M_3'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]
