vlib work
vlib riviera

vlib riviera/xil_defaultlib
vlib riviera/xpm
vlib riviera/axi_infrastructure_v1_1_0
vlib riviera/xil_common_vip_v1_0_0
vlib riviera/smartconnect_v1_0
vlib riviera/axi_protocol_checker_v1_1_14
vlib riviera/axi_vip_v1_0_2
vlib riviera/axi_vip_v1_0_1
vlib riviera/xlconstant_v1_1_3
vlib riviera/lib_cdc_v1_0_2
vlib riviera/proc_sys_reset_v5_0_11
vlib riviera/generic_baseblocks_v2_1_0
vlib riviera/fifo_generator_v13_1_4
vlib riviera/axi_data_fifo_v2_1_12
vlib riviera/axi_register_slice_v2_1_13
vlib riviera/axi_protocol_converter_v2_1_13

vmap xil_defaultlib riviera/xil_defaultlib
vmap xpm riviera/xpm
vmap axi_infrastructure_v1_1_0 riviera/axi_infrastructure_v1_1_0
vmap xil_common_vip_v1_0_0 riviera/xil_common_vip_v1_0_0
vmap smartconnect_v1_0 riviera/smartconnect_v1_0
vmap axi_protocol_checker_v1_1_14 riviera/axi_protocol_checker_v1_1_14
vmap axi_vip_v1_0_2 riviera/axi_vip_v1_0_2
vmap axi_vip_v1_0_1 riviera/axi_vip_v1_0_1
vmap xlconstant_v1_1_3 riviera/xlconstant_v1_1_3
vmap lib_cdc_v1_0_2 riviera/lib_cdc_v1_0_2
vmap proc_sys_reset_v5_0_11 riviera/proc_sys_reset_v5_0_11
vmap generic_baseblocks_v2_1_0 riviera/generic_baseblocks_v2_1_0
vmap fifo_generator_v13_1_4 riviera/fifo_generator_v13_1_4
vmap axi_data_fifo_v2_1_12 riviera/axi_data_fifo_v2_1_12
vmap axi_register_slice_v2_1_13 riviera/axi_register_slice_v2_1_13
vmap axi_protocol_converter_v2_1_13 riviera/axi_protocol_converter_v2_1_13

vlog -work xil_defaultlib  -sv2k12 "+incdir+../../../../final_exam.srcs/sources_1/bd/design_1/ipshared/7e3a/hdl" "+incdir+../../../../final_exam.srcs/sources_1/bd/design_1/ipshared/2ad9/hdl" "+incdir+../../../../final_exam.srcs/sources_1/bd/design_1/ipshared/39ca/hdl/verilog" "+incdir+../../../../final_exam.srcs/sources_1/bd/design_1/ipshared/6eb1/hdl" "+incdir+../../../../final_exam.srcs/sources_1/bd/design_1/ipshared/1d61/hdl" "+incdir+../../../../final_exam.srcs/sources_1/bd/design_1/ipshared/f80f/hdl/verilog" "+incdir+../../../../final_exam.srcs/sources_1/bd/design_1/ipshared/7e3a/hdl" "+incdir+../../../../final_exam.srcs/sources_1/bd/design_1/ipshared/2ad9/hdl" "+incdir+../../../../final_exam.srcs/sources_1/bd/design_1/ipshared/39ca/hdl/verilog" "+incdir+../../../../final_exam.srcs/sources_1/bd/design_1/ipshared/6eb1/hdl" "+incdir+../../../../final_exam.srcs/sources_1/bd/design_1/ipshared/1d61/hdl" "+incdir+../../../../final_exam.srcs/sources_1/bd/design_1/ipshared/f80f/hdl/verilog" \
"C:/Xilinx/Vivado/2017.2/data/ip/xpm/xpm_cdc/hdl/xpm_cdc.sv" \
"C:/Xilinx/Vivado/2017.2/data/ip/xpm/xpm_fifo/hdl/xpm_fifo.sv" \
"C:/Xilinx/Vivado/2017.2/data/ip/xpm/xpm_memory/hdl/xpm_memory.sv" \

vcom -work xpm -93 \
"C:/Xilinx/Vivado/2017.2/data/ip/xpm/xpm_VCOMP.vhd" \

vlog -work axi_infrastructure_v1_1_0  -v2k5 "+incdir+../../../../final_exam.srcs/sources_1/bd/design_1/ipshared/7e3a/hdl" "+incdir+../../../../final_exam.srcs/sources_1/bd/design_1/ipshared/2ad9/hdl" "+incdir+../../../../final_exam.srcs/sources_1/bd/design_1/ipshared/39ca/hdl/verilog" "+incdir+../../../../final_exam.srcs/sources_1/bd/design_1/ipshared/6eb1/hdl" "+incdir+../../../../final_exam.srcs/sources_1/bd/design_1/ipshared/1d61/hdl" "+incdir+../../../../final_exam.srcs/sources_1/bd/design_1/ipshared/f80f/hdl/verilog" "+incdir+../../../../final_exam.srcs/sources_1/bd/design_1/ipshared/7e3a/hdl" "+incdir+../../../../final_exam.srcs/sources_1/bd/design_1/ipshared/2ad9/hdl" "+incdir+../../../../final_exam.srcs/sources_1/bd/design_1/ipshared/39ca/hdl/verilog" "+incdir+../../../../final_exam.srcs/sources_1/bd/design_1/ipshared/6eb1/hdl" "+incdir+../../../../final_exam.srcs/sources_1/bd/design_1/ipshared/1d61/hdl" "+incdir+../../../../final_exam.srcs/sources_1/bd/design_1/ipshared/f80f/hdl/verilog" \
"../../../../final_exam.srcs/sources_1/bd/design_1/ipshared/7e3a/hdl/axi_infrastructure_v1_1_vl_rfs.v" \

vlog -work xil_common_vip_v1_0_0  -sv2k12 "+incdir+../../../../final_exam.srcs/sources_1/bd/design_1/ipshared/7e3a/hdl" "+incdir+../../../../final_exam.srcs/sources_1/bd/design_1/ipshared/2ad9/hdl" "+incdir+../../../../final_exam.srcs/sources_1/bd/design_1/ipshared/39ca/hdl/verilog" "+incdir+../../../../final_exam.srcs/sources_1/bd/design_1/ipshared/6eb1/hdl" "+incdir+../../../../final_exam.srcs/sources_1/bd/design_1/ipshared/1d61/hdl" "+incdir+../../../../final_exam.srcs/sources_1/bd/design_1/ipshared/f80f/hdl/verilog" "+incdir+../../../../final_exam.srcs/sources_1/bd/design_1/ipshared/7e3a/hdl" "+incdir+../../../../final_exam.srcs/sources_1/bd/design_1/ipshared/2ad9/hdl" "+incdir+../../../../final_exam.srcs/sources_1/bd/design_1/ipshared/39ca/hdl/verilog" "+incdir+../../../../final_exam.srcs/sources_1/bd/design_1/ipshared/6eb1/hdl" "+incdir+../../../../final_exam.srcs/sources_1/bd/design_1/ipshared/1d61/hdl" "+incdir+../../../../final_exam.srcs/sources_1/bd/design_1/ipshared/f80f/hdl/verilog" \
"../../../../final_exam.srcs/sources_1/bd/design_1/ipshared/2ad9/hdl/xil_common_vip_v1_0_vl_rfs.sv" \

vlog -work smartconnect_v1_0  -sv2k12 "+incdir+../../../../final_exam.srcs/sources_1/bd/design_1/ipshared/7e3a/hdl" "+incdir+../../../../final_exam.srcs/sources_1/bd/design_1/ipshared/2ad9/hdl" "+incdir+../../../../final_exam.srcs/sources_1/bd/design_1/ipshared/39ca/hdl/verilog" "+incdir+../../../../final_exam.srcs/sources_1/bd/design_1/ipshared/6eb1/hdl" "+incdir+../../../../final_exam.srcs/sources_1/bd/design_1/ipshared/1d61/hdl" "+incdir+../../../../final_exam.srcs/sources_1/bd/design_1/ipshared/f80f/hdl/verilog" "+incdir+../../../../final_exam.srcs/sources_1/bd/design_1/ipshared/7e3a/hdl" "+incdir+../../../../final_exam.srcs/sources_1/bd/design_1/ipshared/2ad9/hdl" "+incdir+../../../../final_exam.srcs/sources_1/bd/design_1/ipshared/39ca/hdl/verilog" "+incdir+../../../../final_exam.srcs/sources_1/bd/design_1/ipshared/6eb1/hdl" "+incdir+../../../../final_exam.srcs/sources_1/bd/design_1/ipshared/1d61/hdl" "+incdir+../../../../final_exam.srcs/sources_1/bd/design_1/ipshared/f80f/hdl/verilog" \
"../../../../final_exam.srcs/sources_1/bd/design_1/ipshared/39ca/hdl/sc_util_v1_0_vl_rfs.sv" \

vlog -work axi_protocol_checker_v1_1_14  -sv2k12 "+incdir+../../../../final_exam.srcs/sources_1/bd/design_1/ipshared/7e3a/hdl" "+incdir+../../../../final_exam.srcs/sources_1/bd/design_1/ipshared/2ad9/hdl" "+incdir+../../../../final_exam.srcs/sources_1/bd/design_1/ipshared/39ca/hdl/verilog" "+incdir+../../../../final_exam.srcs/sources_1/bd/design_1/ipshared/6eb1/hdl" "+incdir+../../../../final_exam.srcs/sources_1/bd/design_1/ipshared/1d61/hdl" "+incdir+../../../../final_exam.srcs/sources_1/bd/design_1/ipshared/f80f/hdl/verilog" "+incdir+../../../../final_exam.srcs/sources_1/bd/design_1/ipshared/7e3a/hdl" "+incdir+../../../../final_exam.srcs/sources_1/bd/design_1/ipshared/2ad9/hdl" "+incdir+../../../../final_exam.srcs/sources_1/bd/design_1/ipshared/39ca/hdl/verilog" "+incdir+../../../../final_exam.srcs/sources_1/bd/design_1/ipshared/6eb1/hdl" "+incdir+../../../../final_exam.srcs/sources_1/bd/design_1/ipshared/1d61/hdl" "+incdir+../../../../final_exam.srcs/sources_1/bd/design_1/ipshared/f80f/hdl/verilog" \
"../../../../final_exam.srcs/sources_1/bd/design_1/ipshared/a1b2/hdl/axi_protocol_checker_v1_1_vl_rfs.sv" \

vlog -work axi_vip_v1_0_2  -sv2k12 "+incdir+../../../../final_exam.srcs/sources_1/bd/design_1/ipshared/7e3a/hdl" "+incdir+../../../../final_exam.srcs/sources_1/bd/design_1/ipshared/2ad9/hdl" "+incdir+../../../../final_exam.srcs/sources_1/bd/design_1/ipshared/39ca/hdl/verilog" "+incdir+../../../../final_exam.srcs/sources_1/bd/design_1/ipshared/6eb1/hdl" "+incdir+../../../../final_exam.srcs/sources_1/bd/design_1/ipshared/1d61/hdl" "+incdir+../../../../final_exam.srcs/sources_1/bd/design_1/ipshared/f80f/hdl/verilog" "+incdir+../../../../final_exam.srcs/sources_1/bd/design_1/ipshared/7e3a/hdl" "+incdir+../../../../final_exam.srcs/sources_1/bd/design_1/ipshared/2ad9/hdl" "+incdir+../../../../final_exam.srcs/sources_1/bd/design_1/ipshared/39ca/hdl/verilog" "+incdir+../../../../final_exam.srcs/sources_1/bd/design_1/ipshared/6eb1/hdl" "+incdir+../../../../final_exam.srcs/sources_1/bd/design_1/ipshared/1d61/hdl" "+incdir+../../../../final_exam.srcs/sources_1/bd/design_1/ipshared/f80f/hdl/verilog" \
"../../../../final_exam.srcs/sources_1/bd/design_1/ipshared/6eb1/hdl/axi_vip_v1_0_vl_rfs.sv" \

vlog -work axi_vip_v1_0_1  -sv2k12 "+incdir+../../../../final_exam.srcs/sources_1/bd/design_1/ipshared/7e3a/hdl" "+incdir+../../../../final_exam.srcs/sources_1/bd/design_1/ipshared/2ad9/hdl" "+incdir+../../../../final_exam.srcs/sources_1/bd/design_1/ipshared/39ca/hdl/verilog" "+incdir+../../../../final_exam.srcs/sources_1/bd/design_1/ipshared/6eb1/hdl" "+incdir+../../../../final_exam.srcs/sources_1/bd/design_1/ipshared/1d61/hdl" "+incdir+../../../../final_exam.srcs/sources_1/bd/design_1/ipshared/f80f/hdl/verilog" "+incdir+../../../../final_exam.srcs/sources_1/bd/design_1/ipshared/7e3a/hdl" "+incdir+../../../../final_exam.srcs/sources_1/bd/design_1/ipshared/2ad9/hdl" "+incdir+../../../../final_exam.srcs/sources_1/bd/design_1/ipshared/39ca/hdl/verilog" "+incdir+../../../../final_exam.srcs/sources_1/bd/design_1/ipshared/6eb1/hdl" "+incdir+../../../../final_exam.srcs/sources_1/bd/design_1/ipshared/1d61/hdl" "+incdir+../../../../final_exam.srcs/sources_1/bd/design_1/ipshared/f80f/hdl/verilog" \
"../../../../final_exam.srcs/sources_1/bd/design_1/ipshared/1d61/hdl/processing_system7_vip_v1_0_vl_rfs.sv" \

vlog -work xil_defaultlib  -v2k5 "+incdir+../../../../final_exam.srcs/sources_1/bd/design_1/ipshared/7e3a/hdl" "+incdir+../../../../final_exam.srcs/sources_1/bd/design_1/ipshared/2ad9/hdl" "+incdir+../../../../final_exam.srcs/sources_1/bd/design_1/ipshared/39ca/hdl/verilog" "+incdir+../../../../final_exam.srcs/sources_1/bd/design_1/ipshared/6eb1/hdl" "+incdir+../../../../final_exam.srcs/sources_1/bd/design_1/ipshared/1d61/hdl" "+incdir+../../../../final_exam.srcs/sources_1/bd/design_1/ipshared/f80f/hdl/verilog" "+incdir+../../../../final_exam.srcs/sources_1/bd/design_1/ipshared/7e3a/hdl" "+incdir+../../../../final_exam.srcs/sources_1/bd/design_1/ipshared/2ad9/hdl" "+incdir+../../../../final_exam.srcs/sources_1/bd/design_1/ipshared/39ca/hdl/verilog" "+incdir+../../../../final_exam.srcs/sources_1/bd/design_1/ipshared/6eb1/hdl" "+incdir+../../../../final_exam.srcs/sources_1/bd/design_1/ipshared/1d61/hdl" "+incdir+../../../../final_exam.srcs/sources_1/bd/design_1/ipshared/f80f/hdl/verilog" \
"../../../bd/design_1/ip/design_1_processing_system7_0_0/sim/design_1_processing_system7_0_0.v" \
"../../../bd/design_1/ipshared/625c/hdl/final_ip_v1_0_S00_AXI.v" \
"../../../bd/design_1/ipshared/625c/hdl/final_ip_v1_0_M00_AXI.v" \
"../../../bd/design_1/ipshared/625c/hdl/final_ip_v1_0.v" \
"../../../bd/design_1/ip/design_1_final_ip_0_0/sim/design_1_final_ip_0_0.v" \
"../../../bd/design_1/ip/design_1_axi_smc_0/bd_0/hdl/bd_afc3.v" \

vlog -work smartconnect_v1_0  -sv2k12 "+incdir+../../../../final_exam.srcs/sources_1/bd/design_1/ipshared/7e3a/hdl" "+incdir+../../../../final_exam.srcs/sources_1/bd/design_1/ipshared/2ad9/hdl" "+incdir+../../../../final_exam.srcs/sources_1/bd/design_1/ipshared/39ca/hdl/verilog" "+incdir+../../../../final_exam.srcs/sources_1/bd/design_1/ipshared/6eb1/hdl" "+incdir+../../../../final_exam.srcs/sources_1/bd/design_1/ipshared/1d61/hdl" "+incdir+../../../../final_exam.srcs/sources_1/bd/design_1/ipshared/f80f/hdl/verilog" "+incdir+../../../../final_exam.srcs/sources_1/bd/design_1/ipshared/7e3a/hdl" "+incdir+../../../../final_exam.srcs/sources_1/bd/design_1/ipshared/2ad9/hdl" "+incdir+../../../../final_exam.srcs/sources_1/bd/design_1/ipshared/39ca/hdl/verilog" "+incdir+../../../../final_exam.srcs/sources_1/bd/design_1/ipshared/6eb1/hdl" "+incdir+../../../../final_exam.srcs/sources_1/bd/design_1/ipshared/1d61/hdl" "+incdir+../../../../final_exam.srcs/sources_1/bd/design_1/ipshared/f80f/hdl/verilog" \
"../../../../final_exam.srcs/sources_1/bd/design_1/ipshared/e870/hdl/sc_axi2sc_v1_0_vl_rfs.sv" \

vlog -work xil_defaultlib  -sv2k12 "+incdir+../../../../final_exam.srcs/sources_1/bd/design_1/ipshared/7e3a/hdl" "+incdir+../../../../final_exam.srcs/sources_1/bd/design_1/ipshared/2ad9/hdl" "+incdir+../../../../final_exam.srcs/sources_1/bd/design_1/ipshared/39ca/hdl/verilog" "+incdir+../../../../final_exam.srcs/sources_1/bd/design_1/ipshared/6eb1/hdl" "+incdir+../../../../final_exam.srcs/sources_1/bd/design_1/ipshared/1d61/hdl" "+incdir+../../../../final_exam.srcs/sources_1/bd/design_1/ipshared/f80f/hdl/verilog" "+incdir+../../../../final_exam.srcs/sources_1/bd/design_1/ipshared/7e3a/hdl" "+incdir+../../../../final_exam.srcs/sources_1/bd/design_1/ipshared/2ad9/hdl" "+incdir+../../../../final_exam.srcs/sources_1/bd/design_1/ipshared/39ca/hdl/verilog" "+incdir+../../../../final_exam.srcs/sources_1/bd/design_1/ipshared/6eb1/hdl" "+incdir+../../../../final_exam.srcs/sources_1/bd/design_1/ipshared/1d61/hdl" "+incdir+../../../../final_exam.srcs/sources_1/bd/design_1/ipshared/f80f/hdl/verilog" \
"../../../bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_5/sim/bd_afc3_s00a2s_0.sv" \

vlog -work smartconnect_v1_0  -sv2k12 "+incdir+../../../../final_exam.srcs/sources_1/bd/design_1/ipshared/7e3a/hdl" "+incdir+../../../../final_exam.srcs/sources_1/bd/design_1/ipshared/2ad9/hdl" "+incdir+../../../../final_exam.srcs/sources_1/bd/design_1/ipshared/39ca/hdl/verilog" "+incdir+../../../../final_exam.srcs/sources_1/bd/design_1/ipshared/6eb1/hdl" "+incdir+../../../../final_exam.srcs/sources_1/bd/design_1/ipshared/1d61/hdl" "+incdir+../../../../final_exam.srcs/sources_1/bd/design_1/ipshared/f80f/hdl/verilog" "+incdir+../../../../final_exam.srcs/sources_1/bd/design_1/ipshared/7e3a/hdl" "+incdir+../../../../final_exam.srcs/sources_1/bd/design_1/ipshared/2ad9/hdl" "+incdir+../../../../final_exam.srcs/sources_1/bd/design_1/ipshared/39ca/hdl/verilog" "+incdir+../../../../final_exam.srcs/sources_1/bd/design_1/ipshared/6eb1/hdl" "+incdir+../../../../final_exam.srcs/sources_1/bd/design_1/ipshared/1d61/hdl" "+incdir+../../../../final_exam.srcs/sources_1/bd/design_1/ipshared/f80f/hdl/verilog" \
"../../../../final_exam.srcs/sources_1/bd/design_1/ipshared/224a/hdl/sc_sc2axi_v1_0_vl_rfs.sv" \

vlog -work xil_defaultlib  -sv2k12 "+incdir+../../../../final_exam.srcs/sources_1/bd/design_1/ipshared/7e3a/hdl" "+incdir+../../../../final_exam.srcs/sources_1/bd/design_1/ipshared/2ad9/hdl" "+incdir+../../../../final_exam.srcs/sources_1/bd/design_1/ipshared/39ca/hdl/verilog" "+incdir+../../../../final_exam.srcs/sources_1/bd/design_1/ipshared/6eb1/hdl" "+incdir+../../../../final_exam.srcs/sources_1/bd/design_1/ipshared/1d61/hdl" "+incdir+../../../../final_exam.srcs/sources_1/bd/design_1/ipshared/f80f/hdl/verilog" "+incdir+../../../../final_exam.srcs/sources_1/bd/design_1/ipshared/7e3a/hdl" "+incdir+../../../../final_exam.srcs/sources_1/bd/design_1/ipshared/2ad9/hdl" "+incdir+../../../../final_exam.srcs/sources_1/bd/design_1/ipshared/39ca/hdl/verilog" "+incdir+../../../../final_exam.srcs/sources_1/bd/design_1/ipshared/6eb1/hdl" "+incdir+../../../../final_exam.srcs/sources_1/bd/design_1/ipshared/1d61/hdl" "+incdir+../../../../final_exam.srcs/sources_1/bd/design_1/ipshared/f80f/hdl/verilog" \
"../../../bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_11/sim/bd_afc3_m00s2a_0.sv" \

vlog -work smartconnect_v1_0  -sv2k12 "+incdir+../../../../final_exam.srcs/sources_1/bd/design_1/ipshared/7e3a/hdl" "+incdir+../../../../final_exam.srcs/sources_1/bd/design_1/ipshared/2ad9/hdl" "+incdir+../../../../final_exam.srcs/sources_1/bd/design_1/ipshared/39ca/hdl/verilog" "+incdir+../../../../final_exam.srcs/sources_1/bd/design_1/ipshared/6eb1/hdl" "+incdir+../../../../final_exam.srcs/sources_1/bd/design_1/ipshared/1d61/hdl" "+incdir+../../../../final_exam.srcs/sources_1/bd/design_1/ipshared/f80f/hdl/verilog" "+incdir+../../../../final_exam.srcs/sources_1/bd/design_1/ipshared/7e3a/hdl" "+incdir+../../../../final_exam.srcs/sources_1/bd/design_1/ipshared/2ad9/hdl" "+incdir+../../../../final_exam.srcs/sources_1/bd/design_1/ipshared/39ca/hdl/verilog" "+incdir+../../../../final_exam.srcs/sources_1/bd/design_1/ipshared/6eb1/hdl" "+incdir+../../../../final_exam.srcs/sources_1/bd/design_1/ipshared/1d61/hdl" "+incdir+../../../../final_exam.srcs/sources_1/bd/design_1/ipshared/f80f/hdl/verilog" \
"../../../../final_exam.srcs/sources_1/bd/design_1/ipshared/986a/hdl/sc_exit_v1_0_vl_rfs.sv" \

vlog -work xil_defaultlib  -sv2k12 "+incdir+../../../../final_exam.srcs/sources_1/bd/design_1/ipshared/7e3a/hdl" "+incdir+../../../../final_exam.srcs/sources_1/bd/design_1/ipshared/2ad9/hdl" "+incdir+../../../../final_exam.srcs/sources_1/bd/design_1/ipshared/39ca/hdl/verilog" "+incdir+../../../../final_exam.srcs/sources_1/bd/design_1/ipshared/6eb1/hdl" "+incdir+../../../../final_exam.srcs/sources_1/bd/design_1/ipshared/1d61/hdl" "+incdir+../../../../final_exam.srcs/sources_1/bd/design_1/ipshared/f80f/hdl/verilog" "+incdir+../../../../final_exam.srcs/sources_1/bd/design_1/ipshared/7e3a/hdl" "+incdir+../../../../final_exam.srcs/sources_1/bd/design_1/ipshared/2ad9/hdl" "+incdir+../../../../final_exam.srcs/sources_1/bd/design_1/ipshared/39ca/hdl/verilog" "+incdir+../../../../final_exam.srcs/sources_1/bd/design_1/ipshared/6eb1/hdl" "+incdir+../../../../final_exam.srcs/sources_1/bd/design_1/ipshared/1d61/hdl" "+incdir+../../../../final_exam.srcs/sources_1/bd/design_1/ipshared/f80f/hdl/verilog" \
"../../../bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_12/sim/bd_afc3_m00e_0.sv" \

vlog -work smartconnect_v1_0  -sv2k12 "+incdir+../../../../final_exam.srcs/sources_1/bd/design_1/ipshared/7e3a/hdl" "+incdir+../../../../final_exam.srcs/sources_1/bd/design_1/ipshared/2ad9/hdl" "+incdir+../../../../final_exam.srcs/sources_1/bd/design_1/ipshared/39ca/hdl/verilog" "+incdir+../../../../final_exam.srcs/sources_1/bd/design_1/ipshared/6eb1/hdl" "+incdir+../../../../final_exam.srcs/sources_1/bd/design_1/ipshared/1d61/hdl" "+incdir+../../../../final_exam.srcs/sources_1/bd/design_1/ipshared/f80f/hdl/verilog" "+incdir+../../../../final_exam.srcs/sources_1/bd/design_1/ipshared/7e3a/hdl" "+incdir+../../../../final_exam.srcs/sources_1/bd/design_1/ipshared/2ad9/hdl" "+incdir+../../../../final_exam.srcs/sources_1/bd/design_1/ipshared/39ca/hdl/verilog" "+incdir+../../../../final_exam.srcs/sources_1/bd/design_1/ipshared/6eb1/hdl" "+incdir+../../../../final_exam.srcs/sources_1/bd/design_1/ipshared/1d61/hdl" "+incdir+../../../../final_exam.srcs/sources_1/bd/design_1/ipshared/f80f/hdl/verilog" \
"../../../../final_exam.srcs/sources_1/bd/design_1/ipshared/f80f/hdl/sc_node_v1_0_vl_rfs.sv" \

vlog -work xil_defaultlib  -sv2k12 "+incdir+../../../../final_exam.srcs/sources_1/bd/design_1/ipshared/7e3a/hdl" "+incdir+../../../../final_exam.srcs/sources_1/bd/design_1/ipshared/2ad9/hdl" "+incdir+../../../../final_exam.srcs/sources_1/bd/design_1/ipshared/39ca/hdl/verilog" "+incdir+../../../../final_exam.srcs/sources_1/bd/design_1/ipshared/6eb1/hdl" "+incdir+../../../../final_exam.srcs/sources_1/bd/design_1/ipshared/1d61/hdl" "+incdir+../../../../final_exam.srcs/sources_1/bd/design_1/ipshared/f80f/hdl/verilog" "+incdir+../../../../final_exam.srcs/sources_1/bd/design_1/ipshared/7e3a/hdl" "+incdir+../../../../final_exam.srcs/sources_1/bd/design_1/ipshared/2ad9/hdl" "+incdir+../../../../final_exam.srcs/sources_1/bd/design_1/ipshared/39ca/hdl/verilog" "+incdir+../../../../final_exam.srcs/sources_1/bd/design_1/ipshared/6eb1/hdl" "+incdir+../../../../final_exam.srcs/sources_1/bd/design_1/ipshared/1d61/hdl" "+incdir+../../../../final_exam.srcs/sources_1/bd/design_1/ipshared/f80f/hdl/verilog" \
"../../../bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_6/sim/bd_afc3_sarn_0.sv" \
"../../../bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_7/sim/bd_afc3_srn_0.sv" \
"../../../bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_8/sim/bd_afc3_sawn_0.sv" \
"../../../bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_9/sim/bd_afc3_swn_0.sv" \
"../../../bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_10/sim/bd_afc3_sbn_0.sv" \

vlog -work smartconnect_v1_0  -sv2k12 "+incdir+../../../../final_exam.srcs/sources_1/bd/design_1/ipshared/7e3a/hdl" "+incdir+../../../../final_exam.srcs/sources_1/bd/design_1/ipshared/2ad9/hdl" "+incdir+../../../../final_exam.srcs/sources_1/bd/design_1/ipshared/39ca/hdl/verilog" "+incdir+../../../../final_exam.srcs/sources_1/bd/design_1/ipshared/6eb1/hdl" "+incdir+../../../../final_exam.srcs/sources_1/bd/design_1/ipshared/1d61/hdl" "+incdir+../../../../final_exam.srcs/sources_1/bd/design_1/ipshared/f80f/hdl/verilog" "+incdir+../../../../final_exam.srcs/sources_1/bd/design_1/ipshared/7e3a/hdl" "+incdir+../../../../final_exam.srcs/sources_1/bd/design_1/ipshared/2ad9/hdl" "+incdir+../../../../final_exam.srcs/sources_1/bd/design_1/ipshared/39ca/hdl/verilog" "+incdir+../../../../final_exam.srcs/sources_1/bd/design_1/ipshared/6eb1/hdl" "+incdir+../../../../final_exam.srcs/sources_1/bd/design_1/ipshared/1d61/hdl" "+incdir+../../../../final_exam.srcs/sources_1/bd/design_1/ipshared/f80f/hdl/verilog" \
"../../../../final_exam.srcs/sources_1/bd/design_1/ipshared/5300/hdl/sc_mmu_v1_0_vl_rfs.sv" \

vlog -work xil_defaultlib  -sv2k12 "+incdir+../../../../final_exam.srcs/sources_1/bd/design_1/ipshared/7e3a/hdl" "+incdir+../../../../final_exam.srcs/sources_1/bd/design_1/ipshared/2ad9/hdl" "+incdir+../../../../final_exam.srcs/sources_1/bd/design_1/ipshared/39ca/hdl/verilog" "+incdir+../../../../final_exam.srcs/sources_1/bd/design_1/ipshared/6eb1/hdl" "+incdir+../../../../final_exam.srcs/sources_1/bd/design_1/ipshared/1d61/hdl" "+incdir+../../../../final_exam.srcs/sources_1/bd/design_1/ipshared/f80f/hdl/verilog" "+incdir+../../../../final_exam.srcs/sources_1/bd/design_1/ipshared/7e3a/hdl" "+incdir+../../../../final_exam.srcs/sources_1/bd/design_1/ipshared/2ad9/hdl" "+incdir+../../../../final_exam.srcs/sources_1/bd/design_1/ipshared/39ca/hdl/verilog" "+incdir+../../../../final_exam.srcs/sources_1/bd/design_1/ipshared/6eb1/hdl" "+incdir+../../../../final_exam.srcs/sources_1/bd/design_1/ipshared/1d61/hdl" "+incdir+../../../../final_exam.srcs/sources_1/bd/design_1/ipshared/f80f/hdl/verilog" \
"../../../bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_2/sim/bd_afc3_s00mmu_0.sv" \

vlog -work smartconnect_v1_0  -sv2k12 "+incdir+../../../../final_exam.srcs/sources_1/bd/design_1/ipshared/7e3a/hdl" "+incdir+../../../../final_exam.srcs/sources_1/bd/design_1/ipshared/2ad9/hdl" "+incdir+../../../../final_exam.srcs/sources_1/bd/design_1/ipshared/39ca/hdl/verilog" "+incdir+../../../../final_exam.srcs/sources_1/bd/design_1/ipshared/6eb1/hdl" "+incdir+../../../../final_exam.srcs/sources_1/bd/design_1/ipshared/1d61/hdl" "+incdir+../../../../final_exam.srcs/sources_1/bd/design_1/ipshared/f80f/hdl/verilog" "+incdir+../../../../final_exam.srcs/sources_1/bd/design_1/ipshared/7e3a/hdl" "+incdir+../../../../final_exam.srcs/sources_1/bd/design_1/ipshared/2ad9/hdl" "+incdir+../../../../final_exam.srcs/sources_1/bd/design_1/ipshared/39ca/hdl/verilog" "+incdir+../../../../final_exam.srcs/sources_1/bd/design_1/ipshared/6eb1/hdl" "+incdir+../../../../final_exam.srcs/sources_1/bd/design_1/ipshared/1d61/hdl" "+incdir+../../../../final_exam.srcs/sources_1/bd/design_1/ipshared/f80f/hdl/verilog" \
"../../../../final_exam.srcs/sources_1/bd/design_1/ipshared/cbcb/hdl/sc_transaction_regulator_v1_0_vl_rfs.sv" \

vlog -work xil_defaultlib  -sv2k12 "+incdir+../../../../final_exam.srcs/sources_1/bd/design_1/ipshared/7e3a/hdl" "+incdir+../../../../final_exam.srcs/sources_1/bd/design_1/ipshared/2ad9/hdl" "+incdir+../../../../final_exam.srcs/sources_1/bd/design_1/ipshared/39ca/hdl/verilog" "+incdir+../../../../final_exam.srcs/sources_1/bd/design_1/ipshared/6eb1/hdl" "+incdir+../../../../final_exam.srcs/sources_1/bd/design_1/ipshared/1d61/hdl" "+incdir+../../../../final_exam.srcs/sources_1/bd/design_1/ipshared/f80f/hdl/verilog" "+incdir+../../../../final_exam.srcs/sources_1/bd/design_1/ipshared/7e3a/hdl" "+incdir+../../../../final_exam.srcs/sources_1/bd/design_1/ipshared/2ad9/hdl" "+incdir+../../../../final_exam.srcs/sources_1/bd/design_1/ipshared/39ca/hdl/verilog" "+incdir+../../../../final_exam.srcs/sources_1/bd/design_1/ipshared/6eb1/hdl" "+incdir+../../../../final_exam.srcs/sources_1/bd/design_1/ipshared/1d61/hdl" "+incdir+../../../../final_exam.srcs/sources_1/bd/design_1/ipshared/f80f/hdl/verilog" \
"../../../bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_3/sim/bd_afc3_s00tr_0.sv" \

vlog -work smartconnect_v1_0  -sv2k12 "+incdir+../../../../final_exam.srcs/sources_1/bd/design_1/ipshared/7e3a/hdl" "+incdir+../../../../final_exam.srcs/sources_1/bd/design_1/ipshared/2ad9/hdl" "+incdir+../../../../final_exam.srcs/sources_1/bd/design_1/ipshared/39ca/hdl/verilog" "+incdir+../../../../final_exam.srcs/sources_1/bd/design_1/ipshared/6eb1/hdl" "+incdir+../../../../final_exam.srcs/sources_1/bd/design_1/ipshared/1d61/hdl" "+incdir+../../../../final_exam.srcs/sources_1/bd/design_1/ipshared/f80f/hdl/verilog" "+incdir+../../../../final_exam.srcs/sources_1/bd/design_1/ipshared/7e3a/hdl" "+incdir+../../../../final_exam.srcs/sources_1/bd/design_1/ipshared/2ad9/hdl" "+incdir+../../../../final_exam.srcs/sources_1/bd/design_1/ipshared/39ca/hdl/verilog" "+incdir+../../../../final_exam.srcs/sources_1/bd/design_1/ipshared/6eb1/hdl" "+incdir+../../../../final_exam.srcs/sources_1/bd/design_1/ipshared/1d61/hdl" "+incdir+../../../../final_exam.srcs/sources_1/bd/design_1/ipshared/f80f/hdl/verilog" \
"../../../../final_exam.srcs/sources_1/bd/design_1/ipshared/cc66/hdl/sc_si_converter_v1_0_vl_rfs.sv" \

vlog -work xil_defaultlib  -sv2k12 "+incdir+../../../../final_exam.srcs/sources_1/bd/design_1/ipshared/7e3a/hdl" "+incdir+../../../../final_exam.srcs/sources_1/bd/design_1/ipshared/2ad9/hdl" "+incdir+../../../../final_exam.srcs/sources_1/bd/design_1/ipshared/39ca/hdl/verilog" "+incdir+../../../../final_exam.srcs/sources_1/bd/design_1/ipshared/6eb1/hdl" "+incdir+../../../../final_exam.srcs/sources_1/bd/design_1/ipshared/1d61/hdl" "+incdir+../../../../final_exam.srcs/sources_1/bd/design_1/ipshared/f80f/hdl/verilog" "+incdir+../../../../final_exam.srcs/sources_1/bd/design_1/ipshared/7e3a/hdl" "+incdir+../../../../final_exam.srcs/sources_1/bd/design_1/ipshared/2ad9/hdl" "+incdir+../../../../final_exam.srcs/sources_1/bd/design_1/ipshared/39ca/hdl/verilog" "+incdir+../../../../final_exam.srcs/sources_1/bd/design_1/ipshared/6eb1/hdl" "+incdir+../../../../final_exam.srcs/sources_1/bd/design_1/ipshared/1d61/hdl" "+incdir+../../../../final_exam.srcs/sources_1/bd/design_1/ipshared/f80f/hdl/verilog" \
"../../../bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_4/sim/bd_afc3_s00sic_0.sv" \

vlog -work xlconstant_v1_1_3  -v2k5 "+incdir+../../../../final_exam.srcs/sources_1/bd/design_1/ipshared/7e3a/hdl" "+incdir+../../../../final_exam.srcs/sources_1/bd/design_1/ipshared/2ad9/hdl" "+incdir+../../../../final_exam.srcs/sources_1/bd/design_1/ipshared/39ca/hdl/verilog" "+incdir+../../../../final_exam.srcs/sources_1/bd/design_1/ipshared/6eb1/hdl" "+incdir+../../../../final_exam.srcs/sources_1/bd/design_1/ipshared/1d61/hdl" "+incdir+../../../../final_exam.srcs/sources_1/bd/design_1/ipshared/f80f/hdl/verilog" "+incdir+../../../../final_exam.srcs/sources_1/bd/design_1/ipshared/7e3a/hdl" "+incdir+../../../../final_exam.srcs/sources_1/bd/design_1/ipshared/2ad9/hdl" "+incdir+../../../../final_exam.srcs/sources_1/bd/design_1/ipshared/39ca/hdl/verilog" "+incdir+../../../../final_exam.srcs/sources_1/bd/design_1/ipshared/6eb1/hdl" "+incdir+../../../../final_exam.srcs/sources_1/bd/design_1/ipshared/1d61/hdl" "+incdir+../../../../final_exam.srcs/sources_1/bd/design_1/ipshared/f80f/hdl/verilog" \
"../../../../final_exam.srcs/sources_1/bd/design_1/ipshared/45df/hdl/xlconstant_v1_1_vl_rfs.v" \

vlog -work xil_defaultlib  -v2k5 "+incdir+../../../../final_exam.srcs/sources_1/bd/design_1/ipshared/7e3a/hdl" "+incdir+../../../../final_exam.srcs/sources_1/bd/design_1/ipshared/2ad9/hdl" "+incdir+../../../../final_exam.srcs/sources_1/bd/design_1/ipshared/39ca/hdl/verilog" "+incdir+../../../../final_exam.srcs/sources_1/bd/design_1/ipshared/6eb1/hdl" "+incdir+../../../../final_exam.srcs/sources_1/bd/design_1/ipshared/1d61/hdl" "+incdir+../../../../final_exam.srcs/sources_1/bd/design_1/ipshared/f80f/hdl/verilog" "+incdir+../../../../final_exam.srcs/sources_1/bd/design_1/ipshared/7e3a/hdl" "+incdir+../../../../final_exam.srcs/sources_1/bd/design_1/ipshared/2ad9/hdl" "+incdir+../../../../final_exam.srcs/sources_1/bd/design_1/ipshared/39ca/hdl/verilog" "+incdir+../../../../final_exam.srcs/sources_1/bd/design_1/ipshared/6eb1/hdl" "+incdir+../../../../final_exam.srcs/sources_1/bd/design_1/ipshared/1d61/hdl" "+incdir+../../../../final_exam.srcs/sources_1/bd/design_1/ipshared/f80f/hdl/verilog" \
"../../../bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_0/sim/bd_afc3_one_0.v" \

vcom -work lib_cdc_v1_0_2 -93 \
"../../../../final_exam.srcs/sources_1/bd/design_1/ipshared/52cb/hdl/lib_cdc_v1_0_rfs.vhd" \

vcom -work proc_sys_reset_v5_0_11 -93 \
"../../../../final_exam.srcs/sources_1/bd/design_1/ipshared/5db7/hdl/proc_sys_reset_v5_0_vh_rfs.vhd" \

vcom -work xil_defaultlib -93 \
"../../../bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_1/sim/bd_afc3_psr_aclk_0.vhd" \

vlog -work xil_defaultlib  -v2k5 "+incdir+../../../../final_exam.srcs/sources_1/bd/design_1/ipshared/7e3a/hdl" "+incdir+../../../../final_exam.srcs/sources_1/bd/design_1/ipshared/2ad9/hdl" "+incdir+../../../../final_exam.srcs/sources_1/bd/design_1/ipshared/39ca/hdl/verilog" "+incdir+../../../../final_exam.srcs/sources_1/bd/design_1/ipshared/6eb1/hdl" "+incdir+../../../../final_exam.srcs/sources_1/bd/design_1/ipshared/1d61/hdl" "+incdir+../../../../final_exam.srcs/sources_1/bd/design_1/ipshared/f80f/hdl/verilog" "+incdir+../../../../final_exam.srcs/sources_1/bd/design_1/ipshared/7e3a/hdl" "+incdir+../../../../final_exam.srcs/sources_1/bd/design_1/ipshared/2ad9/hdl" "+incdir+../../../../final_exam.srcs/sources_1/bd/design_1/ipshared/39ca/hdl/verilog" "+incdir+../../../../final_exam.srcs/sources_1/bd/design_1/ipshared/6eb1/hdl" "+incdir+../../../../final_exam.srcs/sources_1/bd/design_1/ipshared/1d61/hdl" "+incdir+../../../../final_exam.srcs/sources_1/bd/design_1/ipshared/f80f/hdl/verilog" \
"../../../bd/design_1/ip/design_1_axi_smc_0/sim/design_1_axi_smc_0.v" \

vcom -work xil_defaultlib -93 \
"../../../bd/design_1/ip/design_1_rst_ps7_0_100M_0/sim/design_1_rst_ps7_0_100M_0.vhd" \

vlog -work xil_defaultlib  -v2k5 "+incdir+../../../../final_exam.srcs/sources_1/bd/design_1/ipshared/7e3a/hdl" "+incdir+../../../../final_exam.srcs/sources_1/bd/design_1/ipshared/2ad9/hdl" "+incdir+../../../../final_exam.srcs/sources_1/bd/design_1/ipshared/39ca/hdl/verilog" "+incdir+../../../../final_exam.srcs/sources_1/bd/design_1/ipshared/6eb1/hdl" "+incdir+../../../../final_exam.srcs/sources_1/bd/design_1/ipshared/1d61/hdl" "+incdir+../../../../final_exam.srcs/sources_1/bd/design_1/ipshared/f80f/hdl/verilog" "+incdir+../../../../final_exam.srcs/sources_1/bd/design_1/ipshared/7e3a/hdl" "+incdir+../../../../final_exam.srcs/sources_1/bd/design_1/ipshared/2ad9/hdl" "+incdir+../../../../final_exam.srcs/sources_1/bd/design_1/ipshared/39ca/hdl/verilog" "+incdir+../../../../final_exam.srcs/sources_1/bd/design_1/ipshared/6eb1/hdl" "+incdir+../../../../final_exam.srcs/sources_1/bd/design_1/ipshared/1d61/hdl" "+incdir+../../../../final_exam.srcs/sources_1/bd/design_1/ipshared/f80f/hdl/verilog" \
"../../../bd/design_1/hdl/design_1.v" \

vlog -work generic_baseblocks_v2_1_0  -v2k5 "+incdir+../../../../final_exam.srcs/sources_1/bd/design_1/ipshared/7e3a/hdl" "+incdir+../../../../final_exam.srcs/sources_1/bd/design_1/ipshared/2ad9/hdl" "+incdir+../../../../final_exam.srcs/sources_1/bd/design_1/ipshared/39ca/hdl/verilog" "+incdir+../../../../final_exam.srcs/sources_1/bd/design_1/ipshared/6eb1/hdl" "+incdir+../../../../final_exam.srcs/sources_1/bd/design_1/ipshared/1d61/hdl" "+incdir+../../../../final_exam.srcs/sources_1/bd/design_1/ipshared/f80f/hdl/verilog" "+incdir+../../../../final_exam.srcs/sources_1/bd/design_1/ipshared/7e3a/hdl" "+incdir+../../../../final_exam.srcs/sources_1/bd/design_1/ipshared/2ad9/hdl" "+incdir+../../../../final_exam.srcs/sources_1/bd/design_1/ipshared/39ca/hdl/verilog" "+incdir+../../../../final_exam.srcs/sources_1/bd/design_1/ipshared/6eb1/hdl" "+incdir+../../../../final_exam.srcs/sources_1/bd/design_1/ipshared/1d61/hdl" "+incdir+../../../../final_exam.srcs/sources_1/bd/design_1/ipshared/f80f/hdl/verilog" \
"../../../../final_exam.srcs/sources_1/bd/design_1/ipshared/f9c1/hdl/generic_baseblocks_v2_1_vl_rfs.v" \

vlog -work fifo_generator_v13_1_4  -v2k5 "+incdir+../../../../final_exam.srcs/sources_1/bd/design_1/ipshared/7e3a/hdl" "+incdir+../../../../final_exam.srcs/sources_1/bd/design_1/ipshared/2ad9/hdl" "+incdir+../../../../final_exam.srcs/sources_1/bd/design_1/ipshared/39ca/hdl/verilog" "+incdir+../../../../final_exam.srcs/sources_1/bd/design_1/ipshared/6eb1/hdl" "+incdir+../../../../final_exam.srcs/sources_1/bd/design_1/ipshared/1d61/hdl" "+incdir+../../../../final_exam.srcs/sources_1/bd/design_1/ipshared/f80f/hdl/verilog" "+incdir+../../../../final_exam.srcs/sources_1/bd/design_1/ipshared/7e3a/hdl" "+incdir+../../../../final_exam.srcs/sources_1/bd/design_1/ipshared/2ad9/hdl" "+incdir+../../../../final_exam.srcs/sources_1/bd/design_1/ipshared/39ca/hdl/verilog" "+incdir+../../../../final_exam.srcs/sources_1/bd/design_1/ipshared/6eb1/hdl" "+incdir+../../../../final_exam.srcs/sources_1/bd/design_1/ipshared/1d61/hdl" "+incdir+../../../../final_exam.srcs/sources_1/bd/design_1/ipshared/f80f/hdl/verilog" \
"../../../../final_exam.srcs/sources_1/bd/design_1/ipshared/ebc2/simulation/fifo_generator_vlog_beh.v" \

vcom -work fifo_generator_v13_1_4 -93 \
"../../../../final_exam.srcs/sources_1/bd/design_1/ipshared/ebc2/hdl/fifo_generator_v13_1_rfs.vhd" \

vlog -work fifo_generator_v13_1_4  -v2k5 "+incdir+../../../../final_exam.srcs/sources_1/bd/design_1/ipshared/7e3a/hdl" "+incdir+../../../../final_exam.srcs/sources_1/bd/design_1/ipshared/2ad9/hdl" "+incdir+../../../../final_exam.srcs/sources_1/bd/design_1/ipshared/39ca/hdl/verilog" "+incdir+../../../../final_exam.srcs/sources_1/bd/design_1/ipshared/6eb1/hdl" "+incdir+../../../../final_exam.srcs/sources_1/bd/design_1/ipshared/1d61/hdl" "+incdir+../../../../final_exam.srcs/sources_1/bd/design_1/ipshared/f80f/hdl/verilog" "+incdir+../../../../final_exam.srcs/sources_1/bd/design_1/ipshared/7e3a/hdl" "+incdir+../../../../final_exam.srcs/sources_1/bd/design_1/ipshared/2ad9/hdl" "+incdir+../../../../final_exam.srcs/sources_1/bd/design_1/ipshared/39ca/hdl/verilog" "+incdir+../../../../final_exam.srcs/sources_1/bd/design_1/ipshared/6eb1/hdl" "+incdir+../../../../final_exam.srcs/sources_1/bd/design_1/ipshared/1d61/hdl" "+incdir+../../../../final_exam.srcs/sources_1/bd/design_1/ipshared/f80f/hdl/verilog" \
"../../../../final_exam.srcs/sources_1/bd/design_1/ipshared/ebc2/hdl/fifo_generator_v13_1_rfs.v" \

vlog -work axi_data_fifo_v2_1_12  -v2k5 "+incdir+../../../../final_exam.srcs/sources_1/bd/design_1/ipshared/7e3a/hdl" "+incdir+../../../../final_exam.srcs/sources_1/bd/design_1/ipshared/2ad9/hdl" "+incdir+../../../../final_exam.srcs/sources_1/bd/design_1/ipshared/39ca/hdl/verilog" "+incdir+../../../../final_exam.srcs/sources_1/bd/design_1/ipshared/6eb1/hdl" "+incdir+../../../../final_exam.srcs/sources_1/bd/design_1/ipshared/1d61/hdl" "+incdir+../../../../final_exam.srcs/sources_1/bd/design_1/ipshared/f80f/hdl/verilog" "+incdir+../../../../final_exam.srcs/sources_1/bd/design_1/ipshared/7e3a/hdl" "+incdir+../../../../final_exam.srcs/sources_1/bd/design_1/ipshared/2ad9/hdl" "+incdir+../../../../final_exam.srcs/sources_1/bd/design_1/ipshared/39ca/hdl/verilog" "+incdir+../../../../final_exam.srcs/sources_1/bd/design_1/ipshared/6eb1/hdl" "+incdir+../../../../final_exam.srcs/sources_1/bd/design_1/ipshared/1d61/hdl" "+incdir+../../../../final_exam.srcs/sources_1/bd/design_1/ipshared/f80f/hdl/verilog" \
"../../../../final_exam.srcs/sources_1/bd/design_1/ipshared/95b9/hdl/axi_data_fifo_v2_1_vl_rfs.v" \

vlog -work axi_register_slice_v2_1_13  -v2k5 "+incdir+../../../../final_exam.srcs/sources_1/bd/design_1/ipshared/7e3a/hdl" "+incdir+../../../../final_exam.srcs/sources_1/bd/design_1/ipshared/2ad9/hdl" "+incdir+../../../../final_exam.srcs/sources_1/bd/design_1/ipshared/39ca/hdl/verilog" "+incdir+../../../../final_exam.srcs/sources_1/bd/design_1/ipshared/6eb1/hdl" "+incdir+../../../../final_exam.srcs/sources_1/bd/design_1/ipshared/1d61/hdl" "+incdir+../../../../final_exam.srcs/sources_1/bd/design_1/ipshared/f80f/hdl/verilog" "+incdir+../../../../final_exam.srcs/sources_1/bd/design_1/ipshared/7e3a/hdl" "+incdir+../../../../final_exam.srcs/sources_1/bd/design_1/ipshared/2ad9/hdl" "+incdir+../../../../final_exam.srcs/sources_1/bd/design_1/ipshared/39ca/hdl/verilog" "+incdir+../../../../final_exam.srcs/sources_1/bd/design_1/ipshared/6eb1/hdl" "+incdir+../../../../final_exam.srcs/sources_1/bd/design_1/ipshared/1d61/hdl" "+incdir+../../../../final_exam.srcs/sources_1/bd/design_1/ipshared/f80f/hdl/verilog" \
"../../../../final_exam.srcs/sources_1/bd/design_1/ipshared/55c0/hdl/axi_register_slice_v2_1_vl_rfs.v" \

vlog -work axi_protocol_converter_v2_1_13  -v2k5 "+incdir+../../../../final_exam.srcs/sources_1/bd/design_1/ipshared/7e3a/hdl" "+incdir+../../../../final_exam.srcs/sources_1/bd/design_1/ipshared/2ad9/hdl" "+incdir+../../../../final_exam.srcs/sources_1/bd/design_1/ipshared/39ca/hdl/verilog" "+incdir+../../../../final_exam.srcs/sources_1/bd/design_1/ipshared/6eb1/hdl" "+incdir+../../../../final_exam.srcs/sources_1/bd/design_1/ipshared/1d61/hdl" "+incdir+../../../../final_exam.srcs/sources_1/bd/design_1/ipshared/f80f/hdl/verilog" "+incdir+../../../../final_exam.srcs/sources_1/bd/design_1/ipshared/7e3a/hdl" "+incdir+../../../../final_exam.srcs/sources_1/bd/design_1/ipshared/2ad9/hdl" "+incdir+../../../../final_exam.srcs/sources_1/bd/design_1/ipshared/39ca/hdl/verilog" "+incdir+../../../../final_exam.srcs/sources_1/bd/design_1/ipshared/6eb1/hdl" "+incdir+../../../../final_exam.srcs/sources_1/bd/design_1/ipshared/1d61/hdl" "+incdir+../../../../final_exam.srcs/sources_1/bd/design_1/ipshared/f80f/hdl/verilog" \
"../../../../final_exam.srcs/sources_1/bd/design_1/ipshared/f0ae/hdl/axi_protocol_converter_v2_1_vl_rfs.v" \

vlog -work xil_defaultlib  -v2k5 "+incdir+../../../../final_exam.srcs/sources_1/bd/design_1/ipshared/7e3a/hdl" "+incdir+../../../../final_exam.srcs/sources_1/bd/design_1/ipshared/2ad9/hdl" "+incdir+../../../../final_exam.srcs/sources_1/bd/design_1/ipshared/39ca/hdl/verilog" "+incdir+../../../../final_exam.srcs/sources_1/bd/design_1/ipshared/6eb1/hdl" "+incdir+../../../../final_exam.srcs/sources_1/bd/design_1/ipshared/1d61/hdl" "+incdir+../../../../final_exam.srcs/sources_1/bd/design_1/ipshared/f80f/hdl/verilog" "+incdir+../../../../final_exam.srcs/sources_1/bd/design_1/ipshared/7e3a/hdl" "+incdir+../../../../final_exam.srcs/sources_1/bd/design_1/ipshared/2ad9/hdl" "+incdir+../../../../final_exam.srcs/sources_1/bd/design_1/ipshared/39ca/hdl/verilog" "+incdir+../../../../final_exam.srcs/sources_1/bd/design_1/ipshared/6eb1/hdl" "+incdir+../../../../final_exam.srcs/sources_1/bd/design_1/ipshared/1d61/hdl" "+incdir+../../../../final_exam.srcs/sources_1/bd/design_1/ipshared/f80f/hdl/verilog" \
"../../../bd/design_1/ip/design_1_auto_pc_0/sim/design_1_auto_pc_0.v" \

vlog -work xil_defaultlib \
"glbl.v"

