# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/lab4_wrapper.xdc

# Block Designs: bd/lab4/lab4.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==lab4 || ORIG_REF_NAME==lab4}]

# IP: bd/lab4/ip/lab4_processing_system7_0_5/lab4_processing_system7_0_5.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==lab4_processing_system7_0_5 || ORIG_REF_NAME==lab4_processing_system7_0_5}]

# IP: bd/lab4/ip/lab4_my_dma_0_6/lab4_my_dma_0_6.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==lab4_my_dma_0_6 || ORIG_REF_NAME==lab4_my_dma_0_6}]

# IP: bd/lab4/ip/lab4_axi_smc_0/lab4_axi_smc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==lab4_axi_smc_0 || ORIG_REF_NAME==lab4_axi_smc_0}]

# IP: bd/lab4/ip/lab4_rst_ps7_0_100M_3/lab4_rst_ps7_0_100M_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==lab4_rst_ps7_0_100M_3 || ORIG_REF_NAME==lab4_rst_ps7_0_100M_3}]

# IP: bd/lab4/ip/lab4_ps7_0_axi_periph_5/lab4_ps7_0_axi_periph_5.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==lab4_ps7_0_axi_periph_5 || ORIG_REF_NAME==lab4_ps7_0_axi_periph_5}]

# IP: bd/lab4/ip/lab4_auto_pc_0/lab4_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==lab4_auto_pc_0 || ORIG_REF_NAME==lab4_auto_pc_0}]

# XDC: bd/lab4/lab4_ooc.xdc
