# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/0416313_lab4/0416313_lab4.srcs/sources_1/bd/lab4/ip/lab4_axi_smc_0/lab4_axi_smc_0.xci
# IP: The module: 'lab4_axi_smc_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: c:/0416313_lab4/0416313_lab4.srcs/sources_1/bd/lab4/ip/lab4_axi_smc_0/bd_0/bd_6fc9.bd
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/0416313_lab4/0416313_lab4.srcs/sources_1/bd/lab4/ip/lab4_axi_smc_0/bd_0/ip/ip_5/bd_6fc9_s00a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/0416313_lab4/0416313_lab4.srcs/sources_1/bd/lab4/ip/lab4_axi_smc_0/bd_0/ip/ip_11/bd_6fc9_m00s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/0416313_lab4/0416313_lab4.srcs/sources_1/bd/lab4/ip/lab4_axi_smc_0/bd_0/ip/ip_12/bd_6fc9_m00e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/0416313_lab4/0416313_lab4.srcs/sources_1/bd/lab4/ip/lab4_axi_smc_0/bd_0/ip/ip_6/bd_6fc9_sarn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/0416313_lab4/0416313_lab4.srcs/sources_1/bd/lab4/ip/lab4_axi_smc_0/bd_0/ip/ip_7/bd_6fc9_srn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/0416313_lab4/0416313_lab4.srcs/sources_1/bd/lab4/ip/lab4_axi_smc_0/bd_0/ip/ip_8/bd_6fc9_sawn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/0416313_lab4/0416313_lab4.srcs/sources_1/bd/lab4/ip/lab4_axi_smc_0/bd_0/ip/ip_9/bd_6fc9_swn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/0416313_lab4/0416313_lab4.srcs/sources_1/bd/lab4/ip/lab4_axi_smc_0/bd_0/ip/ip_10/bd_6fc9_sbn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/0416313_lab4/0416313_lab4.srcs/sources_1/bd/lab4/ip/lab4_axi_smc_0/bd_0/ip/ip_2/bd_6fc9_s00mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/0416313_lab4/0416313_lab4.srcs/sources_1/bd/lab4/ip/lab4_axi_smc_0/bd_0/ip/ip_3/bd_6fc9_s00tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/0416313_lab4/0416313_lab4.srcs/sources_1/bd/lab4/ip/lab4_axi_smc_0/bd_0/ip/ip_4/bd_6fc9_s00sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/0416313_lab4/0416313_lab4.srcs/sources_1/bd/lab4/ip/lab4_axi_smc_0/bd_0/ip/ip_0/bd_6fc9_one_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/0416313_lab4/0416313_lab4.srcs/sources_1/bd/lab4/ip/lab4_axi_smc_0/bd_0/ip/ip_1/bd_6fc9_psr_aclk_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# XDC: c:/0416313_lab4/0416313_lab4.srcs/sources_1/bd/lab4/ip/lab4_axi_smc_0/bd_0/ip/ip_5/bd_6fc9_s00a2s_0_ooc.xdc

# XDC: c:/0416313_lab4/0416313_lab4.srcs/sources_1/bd/lab4/ip/lab4_axi_smc_0/bd_0/ip/ip_11/bd_6fc9_m00s2a_0_ooc.xdc

# XDC: c:/0416313_lab4/0416313_lab4.srcs/sources_1/bd/lab4/ip/lab4_axi_smc_0/bd_0/ip/ip_6/bd_6fc9_sarn_0_ooc.xdc

# XDC: c:/0416313_lab4/0416313_lab4.srcs/sources_1/bd/lab4/ip/lab4_axi_smc_0/bd_0/ip/ip_7/bd_6fc9_srn_0_ooc.xdc

# XDC: c:/0416313_lab4/0416313_lab4.srcs/sources_1/bd/lab4/ip/lab4_axi_smc_0/bd_0/ip/ip_8/bd_6fc9_sawn_0_ooc.xdc

# XDC: c:/0416313_lab4/0416313_lab4.srcs/sources_1/bd/lab4/ip/lab4_axi_smc_0/bd_0/ip/ip_9/bd_6fc9_swn_0_ooc.xdc

# XDC: c:/0416313_lab4/0416313_lab4.srcs/sources_1/bd/lab4/ip/lab4_axi_smc_0/bd_0/ip/ip_10/bd_6fc9_sbn_0_ooc.xdc

# XDC: c:/0416313_lab4/0416313_lab4.srcs/sources_1/bd/lab4/ip/lab4_axi_smc_0/bd_0/ip/ip_1/bd_6fc9_psr_aclk_0_board.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/0416313_lab4/0416313_lab4.srcs/sources_1/bd/lab4/ip/lab4_axi_smc_0/bd_0/ip/ip_1/bd_6fc9_psr_aclk_0.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/0416313_lab4/0416313_lab4.srcs/sources_1/bd/lab4/ip/lab4_axi_smc_0/ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'lab4_axi_smc_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst]

# IP: C:/0416313_lab4/0416313_lab4.srcs/sources_1/bd/lab4/ip/lab4_axi_smc_0/lab4_axi_smc_0.xci
# IP: The module: 'lab4_axi_smc_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: c:/0416313_lab4/0416313_lab4.srcs/sources_1/bd/lab4/ip/lab4_axi_smc_0/bd_0/bd_6fc9.bd
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/0416313_lab4/0416313_lab4.srcs/sources_1/bd/lab4/ip/lab4_axi_smc_0/bd_0/ip/ip_5/bd_6fc9_s00a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/0416313_lab4/0416313_lab4.srcs/sources_1/bd/lab4/ip/lab4_axi_smc_0/bd_0/ip/ip_11/bd_6fc9_m00s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/0416313_lab4/0416313_lab4.srcs/sources_1/bd/lab4/ip/lab4_axi_smc_0/bd_0/ip/ip_12/bd_6fc9_m00e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/0416313_lab4/0416313_lab4.srcs/sources_1/bd/lab4/ip/lab4_axi_smc_0/bd_0/ip/ip_6/bd_6fc9_sarn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/0416313_lab4/0416313_lab4.srcs/sources_1/bd/lab4/ip/lab4_axi_smc_0/bd_0/ip/ip_7/bd_6fc9_srn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/0416313_lab4/0416313_lab4.srcs/sources_1/bd/lab4/ip/lab4_axi_smc_0/bd_0/ip/ip_8/bd_6fc9_sawn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/0416313_lab4/0416313_lab4.srcs/sources_1/bd/lab4/ip/lab4_axi_smc_0/bd_0/ip/ip_9/bd_6fc9_swn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/0416313_lab4/0416313_lab4.srcs/sources_1/bd/lab4/ip/lab4_axi_smc_0/bd_0/ip/ip_10/bd_6fc9_sbn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/0416313_lab4/0416313_lab4.srcs/sources_1/bd/lab4/ip/lab4_axi_smc_0/bd_0/ip/ip_2/bd_6fc9_s00mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/0416313_lab4/0416313_lab4.srcs/sources_1/bd/lab4/ip/lab4_axi_smc_0/bd_0/ip/ip_3/bd_6fc9_s00tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/0416313_lab4/0416313_lab4.srcs/sources_1/bd/lab4/ip/lab4_axi_smc_0/bd_0/ip/ip_4/bd_6fc9_s00sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/0416313_lab4/0416313_lab4.srcs/sources_1/bd/lab4/ip/lab4_axi_smc_0/bd_0/ip/ip_0/bd_6fc9_one_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/0416313_lab4/0416313_lab4.srcs/sources_1/bd/lab4/ip/lab4_axi_smc_0/bd_0/ip/ip_1/bd_6fc9_psr_aclk_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# XDC: c:/0416313_lab4/0416313_lab4.srcs/sources_1/bd/lab4/ip/lab4_axi_smc_0/bd_0/ip/ip_5/bd_6fc9_s00a2s_0_ooc.xdc

# XDC: c:/0416313_lab4/0416313_lab4.srcs/sources_1/bd/lab4/ip/lab4_axi_smc_0/bd_0/ip/ip_11/bd_6fc9_m00s2a_0_ooc.xdc

# XDC: c:/0416313_lab4/0416313_lab4.srcs/sources_1/bd/lab4/ip/lab4_axi_smc_0/bd_0/ip/ip_6/bd_6fc9_sarn_0_ooc.xdc

# XDC: c:/0416313_lab4/0416313_lab4.srcs/sources_1/bd/lab4/ip/lab4_axi_smc_0/bd_0/ip/ip_7/bd_6fc9_srn_0_ooc.xdc

# XDC: c:/0416313_lab4/0416313_lab4.srcs/sources_1/bd/lab4/ip/lab4_axi_smc_0/bd_0/ip/ip_8/bd_6fc9_sawn_0_ooc.xdc

# XDC: c:/0416313_lab4/0416313_lab4.srcs/sources_1/bd/lab4/ip/lab4_axi_smc_0/bd_0/ip/ip_9/bd_6fc9_swn_0_ooc.xdc

# XDC: c:/0416313_lab4/0416313_lab4.srcs/sources_1/bd/lab4/ip/lab4_axi_smc_0/bd_0/ip/ip_10/bd_6fc9_sbn_0_ooc.xdc

# XDC: c:/0416313_lab4/0416313_lab4.srcs/sources_1/bd/lab4/ip/lab4_axi_smc_0/bd_0/ip/ip_1/bd_6fc9_psr_aclk_0_board.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/0416313_lab4/0416313_lab4.srcs/sources_1/bd/lab4/ip/lab4_axi_smc_0/bd_0/ip/ip_1/bd_6fc9_psr_aclk_0.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/0416313_lab4/0416313_lab4.srcs/sources_1/bd/lab4/ip/lab4_axi_smc_0/ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'lab4_axi_smc_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst]
