# 
# Synthesis run script generated by Vivado
# 

set_param project.vivado.isBlockSynthRun true
set_msg_config -msgmgr_mode ooc_run
create_project -in_memory -part xc7z020clg484-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir C:/0416313_lab4/0416313_lab4.cache/wt [current_project]
set_property parent.project_path C:/0416313_lab4/0416313_lab4.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_FIFO XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part em.avnet.com:zed:part0:1.3 [current_project]
set_property ip_repo_paths c:/0416313_lab4/ip_repo/my_dma_1.0 [current_project]
set_property ip_output_repo c:/0416313_lab4/0416313_lab4.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_ip -quiet C:/0416313_lab4/0416313_lab4.srcs/sources_1/bd/lab4/ip/lab4_axi_smc_0/lab4_axi_smc_0.xci
set_property used_in_implementation false [get_files -all c:/0416313_lab4/0416313_lab4.srcs/sources_1/bd/lab4/ip/lab4_axi_smc_0/bd_0/ip/ip_5/bd_6fc9_s00a2s_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/0416313_lab4/0416313_lab4.srcs/sources_1/bd/lab4/ip/lab4_axi_smc_0/bd_0/ip/ip_11/bd_6fc9_m00s2a_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/0416313_lab4/0416313_lab4.srcs/sources_1/bd/lab4/ip/lab4_axi_smc_0/bd_0/ip/ip_6/bd_6fc9_sarn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/0416313_lab4/0416313_lab4.srcs/sources_1/bd/lab4/ip/lab4_axi_smc_0/bd_0/ip/ip_7/bd_6fc9_srn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/0416313_lab4/0416313_lab4.srcs/sources_1/bd/lab4/ip/lab4_axi_smc_0/bd_0/ip/ip_8/bd_6fc9_sawn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/0416313_lab4/0416313_lab4.srcs/sources_1/bd/lab4/ip/lab4_axi_smc_0/bd_0/ip/ip_9/bd_6fc9_swn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/0416313_lab4/0416313_lab4.srcs/sources_1/bd/lab4/ip/lab4_axi_smc_0/bd_0/ip/ip_10/bd_6fc9_sbn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/0416313_lab4/0416313_lab4.srcs/sources_1/bd/lab4/ip/lab4_axi_smc_0/bd_0/ip/ip_1/bd_6fc9_psr_aclk_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/0416313_lab4/0416313_lab4.srcs/sources_1/bd/lab4/ip/lab4_axi_smc_0/bd_0/ip/ip_1/bd_6fc9_psr_aclk_0.xdc]
set_property used_in_implementation false [get_files -all c:/0416313_lab4/0416313_lab4.srcs/sources_1/bd/lab4/ip/lab4_axi_smc_0/ooc.xdc]
set_property is_locked true [get_files C:/0416313_lab4/0416313_lab4.srcs/sources_1/bd/lab4/ip/lab4_axi_smc_0/lab4_axi_smc_0.xci]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]

set cached_ip [config_ip_cache -export -no_bom -use_project_ipc -dir C:/0416313_lab4/0416313_lab4.runs/lab4_axi_smc_0_synth_1 -new_name lab4_axi_smc_0 -ip [get_ips lab4_axi_smc_0]]

if { $cached_ip eq {} } {

synth_design -top lab4_axi_smc_0 -part xc7z020clg484-1 -mode out_of_context

#---------------------------------------------------------
# Generate Checkpoint/Stub/Simulation Files For IP Cache
#---------------------------------------------------------
catch {
 write_checkpoint -force -noxdef -rename_prefix lab4_axi_smc_0_ lab4_axi_smc_0.dcp

 set ipCachedFiles {}
 write_verilog -force -mode synth_stub -rename_top decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix -prefix decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix_ lab4_axi_smc_0_stub.v
 lappend ipCachedFiles lab4_axi_smc_0_stub.v

 write_vhdl -force -mode synth_stub -rename_top decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix -prefix decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix_ lab4_axi_smc_0_stub.vhdl
 lappend ipCachedFiles lab4_axi_smc_0_stub.vhdl

 write_verilog -force -mode funcsim -rename_top decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix -prefix decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix_ lab4_axi_smc_0_sim_netlist.v
 lappend ipCachedFiles lab4_axi_smc_0_sim_netlist.v

 write_vhdl -force -mode funcsim -rename_top decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix -prefix decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix_ lab4_axi_smc_0_sim_netlist.vhdl
 lappend ipCachedFiles lab4_axi_smc_0_sim_netlist.vhdl

 config_ip_cache -add -dcp lab4_axi_smc_0.dcp -move_files $ipCachedFiles -use_project_ipc -ip [get_ips lab4_axi_smc_0]
}

rename_ref -prefix_all lab4_axi_smc_0_

write_checkpoint -force -noxdef lab4_axi_smc_0.dcp

catch { report_utilization -file lab4_axi_smc_0_utilization_synth.rpt -pb lab4_axi_smc_0_utilization_synth.pb }

if { [catch {
  file copy -force C:/0416313_lab4/0416313_lab4.runs/lab4_axi_smc_0_synth_1/lab4_axi_smc_0.dcp C:/0416313_lab4/0416313_lab4.srcs/sources_1/bd/lab4/ip/lab4_axi_smc_0/lab4_axi_smc_0.dcp
} _RESULT ] } { 
  send_msg_id runtcl-3 error "ERROR: Unable to successfully create or copy the sub-design checkpoint file."
  error "ERROR: Unable to successfully create or copy the sub-design checkpoint file."
}

if { [catch {
  write_verilog -force -mode synth_stub C:/0416313_lab4/0416313_lab4.srcs/sources_1/bd/lab4/ip/lab4_axi_smc_0/lab4_axi_smc_0_stub.v
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create a Verilog synthesis stub for the sub-design. This may lead to errors in top level synthesis of the design. Error reported: $_RESULT"
}

if { [catch {
  write_vhdl -force -mode synth_stub C:/0416313_lab4/0416313_lab4.srcs/sources_1/bd/lab4/ip/lab4_axi_smc_0/lab4_axi_smc_0_stub.vhdl
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create a VHDL synthesis stub for the sub-design. This may lead to errors in top level synthesis of the design. Error reported: $_RESULT"
}

if { [catch {
  write_verilog -force -mode funcsim C:/0416313_lab4/0416313_lab4.srcs/sources_1/bd/lab4/ip/lab4_axi_smc_0/lab4_axi_smc_0_sim_netlist.v
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create the Verilog functional simulation sub-design file. Post-Synthesis Functional Simulation with this file may not be possible or may give incorrect results. Error reported: $_RESULT"
}

if { [catch {
  write_vhdl -force -mode funcsim C:/0416313_lab4/0416313_lab4.srcs/sources_1/bd/lab4/ip/lab4_axi_smc_0/lab4_axi_smc_0_sim_netlist.vhdl
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create the VHDL functional simulation sub-design file. Post-Synthesis Functional Simulation with this file may not be possible or may give incorrect results. Error reported: $_RESULT"
}


} else {


if { [catch {
  file copy -force C:/0416313_lab4/0416313_lab4.runs/lab4_axi_smc_0_synth_1/lab4_axi_smc_0.dcp C:/0416313_lab4/0416313_lab4.srcs/sources_1/bd/lab4/ip/lab4_axi_smc_0/lab4_axi_smc_0.dcp
} _RESULT ] } { 
  send_msg_id runtcl-3 error "ERROR: Unable to successfully create or copy the sub-design checkpoint file."
  error "ERROR: Unable to successfully create or copy the sub-design checkpoint file."
}

if { [catch {
  file rename -force C:/0416313_lab4/0416313_lab4.runs/lab4_axi_smc_0_synth_1/lab4_axi_smc_0_stub.v C:/0416313_lab4/0416313_lab4.srcs/sources_1/bd/lab4/ip/lab4_axi_smc_0/lab4_axi_smc_0_stub.v
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create a Verilog synthesis stub for the sub-design. This may lead to errors in top level synthesis of the design. Error reported: $_RESULT"
}

if { [catch {
  file rename -force C:/0416313_lab4/0416313_lab4.runs/lab4_axi_smc_0_synth_1/lab4_axi_smc_0_stub.vhdl C:/0416313_lab4/0416313_lab4.srcs/sources_1/bd/lab4/ip/lab4_axi_smc_0/lab4_axi_smc_0_stub.vhdl
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create a VHDL synthesis stub for the sub-design. This may lead to errors in top level synthesis of the design. Error reported: $_RESULT"
}

if { [catch {
  file rename -force C:/0416313_lab4/0416313_lab4.runs/lab4_axi_smc_0_synth_1/lab4_axi_smc_0_sim_netlist.v C:/0416313_lab4/0416313_lab4.srcs/sources_1/bd/lab4/ip/lab4_axi_smc_0/lab4_axi_smc_0_sim_netlist.v
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create the Verilog functional simulation sub-design file. Post-Synthesis Functional Simulation with this file may not be possible or may give incorrect results. Error reported: $_RESULT"
}

if { [catch {
  file rename -force C:/0416313_lab4/0416313_lab4.runs/lab4_axi_smc_0_synth_1/lab4_axi_smc_0_sim_netlist.vhdl C:/0416313_lab4/0416313_lab4.srcs/sources_1/bd/lab4/ip/lab4_axi_smc_0/lab4_axi_smc_0_sim_netlist.vhdl
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create the VHDL functional simulation sub-design file. Post-Synthesis Functional Simulation with this file may not be possible or may give incorrect results. Error reported: $_RESULT"
}

}; # end if cached_ip 

if {[file isdir C:/0416313_lab4/0416313_lab4.ip_user_files/ip/lab4_axi_smc_0]} {
  catch { 
    file copy -force C:/0416313_lab4/0416313_lab4.srcs/sources_1/bd/lab4/ip/lab4_axi_smc_0/lab4_axi_smc_0_stub.v C:/0416313_lab4/0416313_lab4.ip_user_files/ip/lab4_axi_smc_0
  }
}

if {[file isdir C:/0416313_lab4/0416313_lab4.ip_user_files/ip/lab4_axi_smc_0]} {
  catch { 
    file copy -force C:/0416313_lab4/0416313_lab4.srcs/sources_1/bd/lab4/ip/lab4_axi_smc_0/lab4_axi_smc_0_stub.vhdl C:/0416313_lab4/0416313_lab4.ip_user_files/ip/lab4_axi_smc_0
  }
}
