webtalk_init -webtalk_dir C:\\Users\\shlab_81\\Desktop\\midterm\\midterm.sdk\\webtalk
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "2018-04-27 12:13:40" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "SDK v2017.2" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2017.2" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "amd64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "SDK" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "false" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "artcsbknugv4tnmisngk4juab3" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "2017.2_2" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "2" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Microsoft Windows 7 , 64-bit" -context "user_environment"
webtalk_add_data -client project -key os_release -value "Service Pack 1  (build 7601)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i3-4150 CPU @ 3.50GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "3491 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "12.000 GB" -context "user_environment"
webtalk_register_client -client sdk
webtalk_add_data -client sdk -key uid -value "1524801254878" -context "sdk\\\\bsp/1524801254878"
webtalk_add_data -client sdk -key hwid -value "1524797588894" -context "sdk\\\\bsp/1524801254878"
webtalk_add_data -client sdk -key os -value "standalone" -context "sdk\\\\bsp/1524801254878"
webtalk_add_data -client sdk -key apptemplate -value "hello_world" -context "sdk\\\\bsp/1524801254878"
webtalk_add_data -client sdk -key RecordType -value "BSPCreation" -context "sdk\\\\bsp/1524801254878"
webtalk_add_data -client sdk -key uid -value "1524801257015" -context "sdk\\\\application/1524801257015"
webtalk_add_data -client sdk -key hwid -value "1524797588894" -context "sdk\\\\application/1524801257015"
webtalk_add_data -client sdk -key bspid -value "1524801254878" -context "sdk\\\\application/1524801257015"
webtalk_add_data -client sdk -key newbsp -value "true" -context "sdk\\\\application/1524801257015"
webtalk_add_data -client sdk -key os -value "standalone" -context "sdk\\\\application/1524801257015"
webtalk_add_data -client sdk -key apptemplate -value "hello_world" -context "sdk\\\\application/1524801257015"
webtalk_add_data -client sdk -key RecordType -value "APPCreation" -context "sdk\\\\application/1524801257015"
webtalk_add_data -client sdk -key LangUsed -value "C" -context "sdk\\\\application/1524801257015"
webtalk_add_data -client sdk -key Procused -value "ps7_cortexa9" -context "sdk\\\\application/1524801257015"
webtalk_add_data -client sdk -key projSize -value "210.1328125" -context "sdk\\\\application/1524801257015"
webtalk_add_data -client sdk -key uid -value "NA" -context "sdk\\\\bsp/1524802419814"
webtalk_add_data -client sdk -key RecordType -value "ToolUsage" -context "sdk\\\\bsp/1524802419814"
webtalk_add_data -client sdk -key BootgenCount -value "0" -context "sdk\\\\bsp/1524802419814"
webtalk_add_data -client sdk -key DebugCount -value "0" -context "sdk\\\\bsp/1524802419814"
webtalk_add_data -client sdk -key PerfCount -value "0" -context "sdk\\\\bsp/1524802419814"
webtalk_add_data -client sdk -key FlashCount -value "0" -context "sdk\\\\bsp/1524802419814"
webtalk_add_data -client sdk -key CrossTriggCount -value "0" -context "sdk\\\\bsp/1524802419814"
webtalk_add_data -client sdk -key QemuDebugCount -value "0" -context "sdk\\\\bsp/1524802419814"
webtalk_transmit -clientid 451754480 -regid "" -xml C:\\Users\\shlab_81\\Desktop\\midterm\\midterm.sdk\\webtalk\\usage_statistics_ext_sdk.xml -html C:\\Users\\shlab_81\\Desktop\\midterm\\midterm.sdk\\webtalk\\usage_statistics_ext_sdk.html -wdm C:\\Users\\shlab_81\\Desktop\\midterm\\midterm.sdk\\webtalk\\sdk_webtalk.wdm -intro "<H3>SDK Usage Report</H3><BR>"
webtalk_terminate
