# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/face/face.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==face || ORIG_REF_NAME==face}]

# IP: bd/face/ip/face_processing_system7_0_0/face_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==face_processing_system7_0_0 || ORIG_REF_NAME==face_processing_system7_0_0}]

# XDC: bd/face/face_ooc.xdc
