# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/midterm_wrapper.xdc

# Block Designs: bd/midterm/midterm.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==midterm || ORIG_REF_NAME==midterm}]

# IP: bd/midterm/ip/midterm_processing_system7_0_0/midterm_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==midterm_processing_system7_0_0 || ORIG_REF_NAME==midterm_processing_system7_0_0}]

# IP: bd/midterm/ip/midterm_matrix_multiplication_0_0/midterm_matrix_multiplication_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==midterm_matrix_multiplication_0_0 || ORIG_REF_NAME==midterm_matrix_multiplication_0_0}]

# IP: bd/midterm/ip/midterm_ps7_0_axi_periph_0/midterm_ps7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==midterm_ps7_0_axi_periph_0 || ORIG_REF_NAME==midterm_ps7_0_axi_periph_0}]

# IP: bd/midterm/ip/midterm_rst_ps7_0_100M_0/midterm_rst_ps7_0_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==midterm_rst_ps7_0_100M_0 || ORIG_REF_NAME==midterm_rst_ps7_0_100M_0}]

# IP: bd/midterm/ip/midterm_auto_pc_0/midterm_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==midterm_auto_pc_0 || ORIG_REF_NAME==midterm_auto_pc_0}]

# XDC: bd/midterm/midterm_ooc.xdc
